# POST http://localhost:3000/signup
# Content-Type: application/json

# {
#     "fullname": "junns",
#     "email":"junssn4xs@gmail.com",
#     "password":"Junn123"
# }

# POST http://localhost:3000/signin
# Content-Type: application/json

# {
#     "email":"junssn4xs@gmail.com",
#     "password":"Junn123"
# }

# GET http://localhost:3000/get-upload-url

# POST http://localhost:3000/create-blog
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2Y2RkYWMwODUyYTFhMjM1MjBjNmU3MCIsImlhdCI6MTcyNDc2NjkxMn0.Kc3FTt7pA4pDjykuPffyn6yrealUiHixc9-eqI4fLRU

# {
#     "title":"ini adalah test titlesdfsdsf",
#     "banner":"https://example.com/image-url",
#     "des":"ini deksripsi singkat",
#     "content": {
#         "blocks":[1,2]
#     },
#     "tags":["tag1","tag2"]
# }

# GET http://localhost:3000/latest-blogs

# GET http://localhost:3000/trending-blogs

# POST http://localhost:3000/search-blogs 
# Content-type:application/json

# {
#     "tag":"tag1"
# }

# POST http://localhost:3000/search-users
# Content-type:application/json

# {
#     "query":"j"
# }

# POST http://localhost:3000/get-profile
# Content-type:application/json

# {
#     "username":"junssn4xs"
# }


POST http://localhost:3000/get-blog
Content-type:application/json

{
    "blog_id":"ini-adalah-test-title-NL4Ej3qXBIwhjGogxUxi"
}